server:
  port: 8961
spring:
  application:
    name: qiuhuu-resource
  profiles:
    active: dev

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:8960/oauth/token
      user-authorization-uri: http://localhost:8960/oauth/authorize
    resource:
      token-info-uri: http://localhost:8960/oauth/check_token