#management:
#  endpoint:
#    health:
#      show-details: always
mybatis:
  type-aliases-package: com.qiuhuu.test.domain.entity
  mapper-locations: classpath:mybatis/mapping/*.xml
  config-location: classpath:mybatis/mybatis.xml

